### ISSUE TITLE
変数展開

### ISSUE THREAD

**Issue by tk1225** [tk1225/minishell#24]
単語に含まれる $USER のような変数を展開し、" ' の除去も行います。

**Comment by Ashes110** [comment]
\の後が \, $, ", upper, lowerで色々ちがう

**Comment by Ashes110** [comment]
"\""   ->  "
\"       ->  "

"\'"    ->  \'
\'        ->  '

**Comment by Ashes110** [comment]
綺麗に渡されたら展開はできるようになっている

いろんなパターンに未対応

**Comment by Ashes110** [comment]
$?を0固定にしているのでのちに変更
